name: EAS Build

on:
  push:
    branches:
      - main

jobs:
  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_GO_TOKEN }}

      - name: Check logged user
        run: eas whoami

      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive